// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGI6gQ-bs0HILl6hwzcy-u6AYOj7AQFA8',
    appId: '1:570307881126:web:2fa93e7b3cfc70a9c66c67',
    messagingSenderId: '570307881126',
    projectId: 'expense-tracker-f80cc',
    authDomain: 'expense-tracker-f80cc.firebaseapp.com',
    storageBucket: 'expense-tracker-f80cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRjERVpP2ambD0G7jpHNO-YeCGsHSWwHU',
    appId: '1:570307881126:android:e402043fd4eebaa8c66c67',
    messagingSenderId: '570307881126',
    projectId: 'expense-tracker-f80cc',
    storageBucket: 'expense-tracker-f80cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAclFcM-NZOPPh5RjgwY1mkDx3cx0cp87Q',
    appId: '1:570307881126:ios:941c415cb801762bc66c67',
    messagingSenderId: '570307881126',
    projectId: 'expense-tracker-f80cc',
    storageBucket: 'expense-tracker-f80cc.appspot.com',
    iosBundleId: 'com.example.expensetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAclFcM-NZOPPh5RjgwY1mkDx3cx0cp87Q',
    appId: '1:570307881126:ios:10a286748d641ef2c66c67',
    messagingSenderId: '570307881126',
    projectId: 'expense-tracker-f80cc',
    storageBucket: 'expense-tracker-f80cc.appspot.com',
    iosBundleId: 'com.example.expensetracker.RunnerTests',
  );
}
